name: tokokue
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
    
  # Cupertino Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1
  
  # Network
  http: ^1.2.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Location
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  location: ^5.0.0

  # Encryption
  crypto: ^3.0.3
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Currency & Time
  intl: ^0.19.0
  timezone: ^0.9.2
  
  # UI
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  
  # rive
  rive: 0.13.20
  
  # Audio for game
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgroundgame.jpg
    - assets/images/cake.png
    - assets/images/chef.webp
    - assets/images/Home.png
    - assets/animation/
    - assets/cute.mp3
    - pou-main/audio/eat.wav

